# Generated by Django 5.1.8 on 2025-12-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_slug_alter_product_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariation',
            name='unique_variation_options',
        ),
    ]
