# Generated by Django 5.1.8 on 2025-12-27 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_productvariation_unique_variation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationoption',
            name='type',
        ),
        migrations.AddField(
            model_name='variationoption',
            name='kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variation_options', to='catalog.variationkind'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variationoption',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variation_options', to='catalog.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VariationType',
        ),
    ]
