# Generated by Django 5.1.8 on 2026-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_wishlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variationoption',
            options={'ordering': ['name']},
        ),
        migrations.AddConstraint(
            model_name='variationoption',
            constraint=models.UniqueConstraint(fields=('kind', 'product', 'name'), name='unique_variation_option'),
        ),
    ]
