# Generated by Django 5.1.8 on 2026-03-26 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_variationoption_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variationkind",
            name="sku_abbr",
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Price must be at least 1."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        20, message="The description must have at least 20 characters"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        6, message="Name must have at least 6 characters"
                    )
                ],
            ),
        ),
    ]
