# Generated by Django 5.1.8 on 2026-03-26 13:03

from django.db import migrations


def populate_sku_abbr(apps, schema_editor):
    VariationKind = apps.get_model("catalog", "VariationKind")

    for obj in VariationKind.objects.filter(sku_abbr__isnull=True):
        obj.sku_abbr = obj.name[:3].upper()
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_variationkind_sku_abbr_alter_product_base_price_and_more"),
    ]

    operations = [migrations.RunPython(populate_sku_abbr)]
