# Generated by Django 6.0.2 on 2026-03-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_auto_20260326_1003"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="final_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
