# Generated by Django 6.0.2 on 2026-04-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_productvariation_final_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariation",
            name="final_price",
        ),
    ]
