# Generated by Django 6.0.2 on 2026-04-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_remove_productvariation_final_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
