# Generated by Django 6.0.2 on 2026-04-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productvariation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='productvariation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('product',), name='unique_base_variant_per_product'),
        ),
    ]
