/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AdminVariationKindsRouteImport } from './routes/admin/variation-kinds'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AppWishlistRouteImport } from './routes/_app/wishlist'
import { Route as AppCollectionsRouteImport } from './routes/_app/collections'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products_.new'
import { Route as AppProductsSlugRouteImport } from './routes/_app/products.$slug'
import { Route as AppCollectionsSlugRouteImport } from './routes/_app/collections_.$slug'
import { Route as AppAuthLoginRouteImport } from './routes/_app/_auth/login'
import { Route as AdminProductsPostSlugEditRouteImport } from './routes/admin/products_.$postSlug.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminVariationKindsRoute = AdminVariationKindsRouteImport.update({
  id: '/variation-kinds',
  path: '/variation-kinds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AppWishlistRoute = AppWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AppProductsSlugRoute = AppProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsSlugRoute = AppCollectionsSlugRouteImport.update({
  id: '/collections_/$slug',
  path: '/collections/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthLoginRoute = AppAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppAuthRoute,
} as any)
const AdminProductsPostSlugEditRoute =
  AdminProductsPostSlugEditRouteImport.update({
    id: '/products_/$postSlug/edit',
    path: '/products/$postSlug/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/collections': typeof AppCollectionsRoute
  '/wishlist': typeof AppWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/variation-kinds': typeof AdminVariationKindsRoute
  '/admin/': typeof AdminIndexRoute
  '/login': typeof AppAuthLoginRoute
  '/collections/$slug': typeof AppCollectionsSlugRoute
  '/products/$slug': typeof AppProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/$postSlug/edit': typeof AdminProductsPostSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/collections': typeof AppCollectionsRoute
  '/wishlist': typeof AppWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/variation-kinds': typeof AdminVariationKindsRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof AppAuthLoginRoute
  '/collections/$slug': typeof AppCollectionsSlugRoute
  '/products/$slug': typeof AppProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/$postSlug/edit': typeof AdminProductsPostSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/wishlist': typeof AppWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/variation-kinds': typeof AdminVariationKindsRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/_auth/login': typeof AppAuthLoginRoute
  '/_app/collections_/$slug': typeof AppCollectionsSlugRoute
  '/_app/products/$slug': typeof AppProductsSlugRoute
  '/admin/products_/new': typeof AdminProductsNewRoute
  '/admin/products_/$postSlug/edit': typeof AdminProductsPostSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/collections'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/products'
    | '/admin/variation-kinds'
    | '/admin/'
    | '/login'
    | '/collections/$slug'
    | '/products/$slug'
    | '/admin/products/new'
    | '/admin/products/$postSlug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/products'
    | '/admin/variation-kinds'
    | '/admin'
    | '/login'
    | '/collections/$slug'
    | '/products/$slug'
    | '/admin/products/new'
    | '/admin/products/$postSlug/edit'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/_auth'
    | '/_app/collections'
    | '/_app/wishlist'
    | '/admin/categories'
    | '/admin/products'
    | '/admin/variation-kinds'
    | '/_app/'
    | '/admin/'
    | '/_app/_auth/login'
    | '/_app/collections_/$slug'
    | '/_app/products/$slug'
    | '/admin/products_/new'
    | '/admin/products_/$postSlug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/variation-kinds': {
      id: '/admin/variation-kinds'
      path: '/variation-kinds'
      fullPath: '/admin/variation-kinds'
      preLoaderRoute: typeof AdminVariationKindsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/wishlist': {
      id: '/_app/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AppWishlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/products_/new': {
      id: '/admin/products_/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/products/$slug': {
      id: '/_app/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof AppProductsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections_/$slug': {
      id: '/_app/collections_/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof AppCollectionsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth/login': {
      id: '/_app/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppAuthLoginRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/admin/products_/$postSlug/edit': {
      id: '/admin/products_/$postSlug/edit'
      path: '/products/$postSlug/edit'
      fullPath: '/admin/products/$postSlug/edit'
      preLoaderRoute: typeof AdminProductsPostSlugEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AppAuthRouteChildren {
  AppAuthLoginRoute: typeof AppAuthLoginRoute
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthLoginRoute: AppAuthLoginRoute,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppWishlistRoute: typeof AppWishlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCollectionsSlugRoute: typeof AppCollectionsSlugRoute
  AppProductsSlugRoute: typeof AppProductsSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppCollectionsRoute: AppCollectionsRoute,
  AppWishlistRoute: AppWishlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppCollectionsSlugRoute: AppCollectionsSlugRoute,
  AppProductsSlugRoute: AppProductsSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminVariationKindsRoute: typeof AdminVariationKindsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsPostSlugEditRoute: typeof AdminProductsPostSlugEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminVariationKindsRoute: AdminVariationKindsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsPostSlugEditRoute: AdminProductsPostSlugEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
